name: mip

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  http: ^1.2.0
  provider: ^6.1.2
  objectbox: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7