name: mip
version: 1.1.0+1
description: Managing Industrial Printers (mip)
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.0.0
  http: ^1.2.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  device_info_plus: ^10.0.1

flutter:
  uses-material-design: true

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^3.0.1